@startuml

' Définition des tables

entity "user" as User {
  + **user_id (PK)** : int
  --
  mail : varchar(100) [UNIQUE]
  password : varchar(100)
  name : varchar(100)
  firstname : varchar(100)
  role : int
}

entity "series" as Series {
  + **series_id (PK)** : int
  --
  title : varchar(100)
  description : text
  img : varchar(100)
  year : int
  date_added : date
  --
  # genre_id (FK) : int
}

entity "episode" as Episode {
  + **episode_id (PK)** : int
  --
  num : int
  title : varchar(100)
  summary : text
  duration : int
  file : varchar(100)
  img : varchar(100)
  --
  # series_id (FK) : int
}

entity "genre" as Genre {
  + **genre_id (PK)** : int
  --
  name : varchar(100) [UNIQUE]
}

' Tables d'association

entity "commentary" as Commentary {
  + **user_id (PK, FK)** : int
  + **series_id (PK, FK)** : int
  --
  text : text
  date_added : datetime
}

entity "notation" as Notation {
  + **user_id (PK, FK)** : int
  + **series_id (PK, FK)** : int
  --
  note : number
  date_added : datetime
}

entity "like_list" as LikeList {
  + **user_id (PK, FK)** : int
  + **series_id (PK, FK)** : int
}

entity "watch_episode" as WatchEpisode {
  + **user_id (PK, FK)** : int
  + **episode_id (PK, FK)** : int
  --
  viewing_date : datetime
}


' Définition des relations
Genre -- Series : "concerne 0..N"


' Tables de liaison
User -- Commentary : "écrit 0..N"
Series -- Commentary : "reçoit 0..N"

User -- Notation : "écrit 0..N"
Series -- Notation : "reçoit 0..N"

User -- LikeList : "préfère 0..N"
Series -- LikeList : "est préféré par 0..N"

User -- WatchEpisode : "visionne 0..N"
Episode -- WatchEpisode : "est visionné par 0..N"


@enduml